import type { ArchitectureSession } from "../connector/types";
import type { DocumentKind } from "../connector/personas";

const ALL: DocumentKind[] = [
  "market",
  "procedure",
  "procurement",
  "ip",
  "finance",
  "presentation",
];

/**
 * Pure domain function: build a single-file research-pack Markdown bundle
 * from a completed market-research session. Extracted for unit testing.
 */
export function buildSolutionPack(session: ArchitectureSession): string {
  const parts: string[] = [];
  parts.push(`# ${session.title} — Market Research Pack\n`);
  parts.push(
    `_Generated by Market Research Group on ${new Date(session.createdAt).toLocaleDateString()}. Debate threshold: ${session.settings.threshold}%, max ${session.settings.maxRounds} rounds per department._\n`,
  );
  parts.push(`\n## Original Idea\n\n${session.idea}\n`);
  if (session.refinedIdea) {
    parts.push(`\n---\n\n## Refined Concept\n\n${session.refinedIdea.content}\n`);
  }
  for (const kind of ALL) {
    const art = session.artifacts.find((a) => a.kind === kind);
    if (!art) continue;
    parts.push(`\n---\n\n## ${art.title}\n`);
    if (art.terminatedBy) {
      parts.push(
        `_Department debate: ${art.rounds.length} round(s), terminated by ${art.terminatedBy}._\n`,
      );
    }
    if (art.error) parts.push(`\n> ⚠ Generation error: ${art.error}\n`);
    else parts.push(`\n${art.content}\n`);
  }
  return parts.join("");
}

/**
 * Pure helper: slugify a session title for a downloadable file name.
 */
export function slugifySessionTitle(s: string): string {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "session"
  );
}
